version: "3"
#x-aws-vpc: <Defines VPC using VPC id>
#x-aws-cluster: <Defines ECS cluster using cluster ARN>
#x-aws-loadbalancer: <Defines ALB using ALB name>

#All Services pull from .env file
services:
    userms:
       image: "${userImage}"
       ports:
           - target: ${userPort}
             x-aws-protocol: http
    loansms:
       image: "${loansImage}"
       ports:
           - target: ${loansPort}
             x-aws-protocol: http
    branchesms:
       image: ${branchesImage}
       ports:
           - target: ${branchesPort}
             x-aws-protocol: http
