version: "3"
<<<<<<< Updated upstream
#x-aws-vpc: <Defines VPC using VPC id>
#x-aws-cluster: <Defines ECS cluster using cluster ARN>
#x-aws-loadbalancer: <Defines ALB using ALB name>

#All Services pull from .env file
services:
    userms:
       image: "${userImage}"
       ports:
           - target: ${userPort}
             x-aws-protocol: http
    loansms:
       image: "${loansImage}"
       ports:
           - target: ${loansPort}
             x-aws-protocol: http
    branchesms:
       image: ${branchesImage}
       ports:
           - target: ${branchesPort}
             x-aws-protocol: http
=======
x-aws-vpc: "vpc-0c2fd729f25af836f" #Variablize
#x-aws-cluster: "cashmoney" #Change to cashmoney
x-aws-loadbalancer: "cashmoney-alb" #Change to cashmoney alb
services:
  userms:
    image: "202447729588.dkr.ecr.us-east-1.amazonaws.com/user-ms"
    ports:
      - target: 8000
        x-aws-protocol: http
>>>>>>> Stashed changes
