AWSTemplateFormatVersion: 2010-09-09
Resources:
  BranchesmsListener:
    Properties:
      DefaultActions:
      - ForwardConfig:
          TargetGroups:
          - TargetGroupArn:
              Ref: BranchesmsTargetGroup
        Type: forward
      LoadBalancerArn:
        Ref: LoadBalancer
      Port: 8080
      Protocol: HTTP
    Type: AWS::ElasticLoadBalancingV2::Listener
  BranchesmsTargetGroup:
    Properties:
      Port: 8080
      Protocol: HTTP
      Tags:
      - Key: com.docker.compose.project
        Value: docker-compose
      TargetType: ip
      VpcId: vpc-3661fb5d
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
  BranchesmsService:
    DependsOn:
    - BranchesmsListener
    Properties:
      Cluster:
        Fn::GetAtt:
        - Cluster
        - Arn
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DeploymentController:
        Type: ECS
      DesiredCount: 1
      LaunchType: FARGATE
      LoadBalancers:
      - ContainerName: branchesms
        ContainerPort: 8080
        TargetGroupArn:
          Ref: BranchesmsTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
          - Ref: DefaultNetwork
          Subnets:
          - subnet-ef1e3da3
          - subnet-e4a45f99
          - subnet-d223a1b9
      PlatformVersion: 1.4.0
      PropagateTags: SERVICE
      SchedulingStrategy: REPLICA
      ServiceRegistries:
      - RegistryArn:
          Fn::GetAtt:
          - BranchesmsServiceDiscoveryEntry
          - Arn
      Tags:
      - Key: com.docker.compose.project
        Value: docker-compose
      - Key: com.docker.compose.service
        Value: branchesms
      TaskDefinition:
        Ref: BranchesmsTaskDefinition
    Type: AWS::ECS::Service
  BranchesmsServiceDiscoveryEntry:
    Properties:
      Description: '"branchesms" service discovery entry in Cloud Map'
      DnsConfig:
        DnsRecords:
        - TTL: 60
          Type: A
        RoutingPolicy: MULTIVALUE
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Name: branchesms
      NamespaceId:
        Ref: CloudMap
    Type: AWS::ServiceDiscovery::Service
  BranchesmsTaskDefinition:
    Properties:
      ContainerDefinitions:
      - Command:
        - us-east-2.compute.internal
        - docker-compose.local
        Essential: false
        Image: docker/ecs-searchdomain-sidecar:1.0
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group:
              Ref: LogGroup
            awslogs-region:
              Ref: AWS::Region
            awslogs-stream-prefix: docker-compose
        Name: Branchesms_ResolvConf_InitContainer
      - DependsOn:
        - Condition: SUCCESS
          ContainerName: Branchesms_ResolvConf_InitContainer
        Essential: true
        Image: 202447729588.dkr.ecr.us-east-2.amazonaws.com/branches-ms:latest@sha256:7891184f31d3407182bcd9453da92017f2f846429a9f1312d8ff8a87af757173
        LinuxParameters: {}
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group:
              Ref: LogGroup
            awslogs-region:
              Ref: AWS::Region
            awslogs-stream-prefix: docker-compose
        Name: branchesms
        PortMappings:
        - ContainerPort: 8080
          HostPort: 8080
      Cpu: "256"
      ExecutionRoleArn:
        Ref: BranchesmsTaskExecutionRole
      Family: docker-compose-branchesms
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
      - FARGATE
    Type: AWS::ECS::TaskDefinition
  BranchesmsTaskExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Condition: {}
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Tags:
      - Key: com.docker.compose.project
        Value: docker-compose
      - Key: com.docker.compose.service
        Value: branchesms
    Type: AWS::IAM::Role
  CloudMap:
    Properties:
      Description: Service Map for Docker Compose project docker-compose
      Name: docker-compose.local
      Vpc: vpc-3661fb5d
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
  Cluster:
    Properties:
      ClusterName: docker-compose
      Tags:
      - Key: com.docker.compose.project
        Value: docker-compose
    Type: AWS::ECS::Cluster
  Default8000Ingress:
    Properties:
      CidrIp: 0.0.0.0/0
      Description: userms:8000/ on default network
      FromPort: 8000
      GroupId:
        Ref: DefaultNetwork
      IpProtocol: "-1"
      ToPort: 8000
    Type: AWS::EC2::SecurityGroupIngress
  DefaultNetwork:
    Properties:
      GroupDescription: docker-compose Security Group for default network
      Tags:
      - Key: com.docker.compose.project
        Value: docker-compose
      - Key: com.docker.compose.network
        Value: docker-compose_default
      VpcId: vpc-3661fb5d
    Type: AWS::EC2::SecurityGroup
  DefaultNetworkIngress:
    Properties:
      Description: Allow communication within network default
      GroupId:
        Ref: DefaultNetwork
      IpProtocol: "-1"
      SourceSecurityGroupId:
        Ref: DefaultNetwork
    Type: AWS::EC2::SecurityGroupIngress
  LoadBalancer:
    Properties:
      Scheme: internet-facing
      SecurityGroups:
      - Ref: DefaultNetwork
      Subnets:
      - subnet-ef1e3da3
      - subnet-e4a45f99
      - subnet-d223a1b9
      Tags:
      - Key: com.docker.compose.project
        Value: docker-compose
      Type: application
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
  LogGroup:
    Properties:
      LogGroupName: /docker-compose/docker-compose
    Type: AWS::Logs::LogGroup
