apiVersion: v1
kind: Service
metadata:
  labels:
    run: branchesms-service
  name: branchesms-service
spec:
  selector:
    app: branchesms-dep
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: branchesms-dep
  name: branchesms-dep
spec:
  replicas: 3
  strategy:
     type: RollingUpdate
     rollingUpdate:
        maxSurge: 2
        maxUnavailable: 0
  selector:
    matchLabels:
      app: branchesms-dep
  template:
    metadata:
      labels:
        app: branchesms-dep
    spec:
      containers:
      - image: branches-ms:latest
        imagePullPolicy: Never
        name: branchesms-dep
        ports:
        - containerPort: 8080
