apiVersion: v1
kind: Service
metadata:
  labels:
    run: userms-service
  name: userms-service
spec:
  selector:
    app: userms-dep
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: userms-dep
  name: userms-dep
spec:
  replicas: 3
  strategy:
     type: RollingUpdate
     rollingUpdate:
        maxSurge: 2
        maxUnavailable: 0
  selector:
    matchLabels:
      app: userms-dep
  template:
    metadata:
      labels:
        app: userms-dep
    spec:
      containers:
      - image: user-ms:latest
        imagePullPolicy: Never
        name: userms-dep
        ports:
        - containerPort: 8000
