apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: branchesms
  name: branchesms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: branchesms
  strategy: {}
  template:
    metadata:
      labels:
        app: branchesms
    spec:
      containers:
      - image: ucm-branchesms:latest
        name: branchesms
        imagePullPolicy: Never
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: branchesms
  name: branchesms
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: branchesms
  type: ClusterIP
status:
  loadBalancer: {}
