apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: userms
  name: userms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userms
  strategy: {}
  template:
    metadata:
      labels:
        app: userms
    spec:
      containers:
      - image: ucm-userms:latest
        name: userms
        imagePullPolicy: Never
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: userms
  name: userms
spec:
  ports:
  - name: 8000-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: userms
  type: ClusterIP
status:
  loadBalancer: {}
